apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-config
  namespace: traefik
spec:
  encryptedData:
    config.yaml: AgCdaKzVrk30bqnbBBbzW1qgw1a2qgIqFYkFz6AjPlM7clihzObINYeYAMPF4pYokOjL5JBeHiBVYqHS8O9oP0Ly+0mDvh0ppiMJBVL6cVGQ4X8d1I0K6i+bE9wgN43EhZ3Eki+D+6NSG9OwSICwlg67yvKcMlYj680+hPANv9biOhcWC7a6/HRTn4tsGJ9ENIH06jeFSxmDDn+PEQqQYbAkQYsqMPLzV1QnM1R6WYAcgiC6Rxe+5Yox8IOTJRcs6J8MDPto2vH8wTyeUNdou8gYxsf75+PwEO0YEDtDS8etyHFhffaqa171WGuYzdcwr9S3RNu2LLSe7GbrXQBGrCRlScoqiAXQX+f0Or12VG7Bq/hSIJSJsCB01Ksm7/laUW/gAf7+1ZAVt6uhD777PdV/Ol4zEzHoLGkBo17g5H0R/9EdAI4cePh2nAa+5Z/PkqjaQ0nB1ufLtGHTJXNr/etvHKZoSodRmlu43koFc6JFXN+u9SzrALkzI8Bi5NlAJQEhZsd4PR/zvPYEn9I3t3rG9nHId/ogkVrs7pDpw2whgPwgOw2A/g+wxmqPME+itYcBLadQreH4wokeh532J0WzTcyOcfIvx8VDgggBE5RN2u5IcWfp4w0sDPQObgAh4Yoz7Is1YlMdEiR+b7tMEV6YQN53fL0oaRTk2NsLeK5Jwcqdb48hVRyqpHNGyRbRAqeEucPNfPyV55KDRmqIY6bugpeNqgLgYhHn6D//WMYxZd8SFs/l5eIAWgNZFnqKFWBlYrNlFZQqxbw+P4JGwZD2X1MqkZNUFBX/6lmfv5Yl6XaqlW9ezUb+p6rdSoHZ6QzjaZhEG698xMB5desRMtEdHy2OffYALEPhLd4T7EWiixd85ZyYUek8bjm998ESARiGjwjcV3taD/0Ed19d1qAGJ3L0wCyLk1uMiH1rHdZyr8XhNbIXP1HYFJX9jgn8cz6Y3uOQBvfjTPVS0bwgChr2ZKLbVKmFoaRVQQ7vMvRRuGUcC4jxYaFUS4c2Yk6D/598hoL9bXcTaJW2WcnV9SB521hpExCCIHgp9r5o94ZAUPsNexUfxxhsnouwYzfEj7EZsjeD/Zi4d/2m8253tqcLtrua+bMISc/r5SKKSFFPGvqFEE52ZSmTAF95mVM+7STh8NGLGtTiu8ZmWxzCc7Pu36ebK49nrlgt+9jqf7toHyRStRE7JSswJPXddHC592ZjUtxiWGuJClZ96eZBe6Ua3Kj/L4VZ/BrxzHyERaRtu9hjzBybwhe28gHcc2fI36GP+1D3FHmil4AtIdTyPncJcUdQtxBhP1Gc73ND
  template:
    metadata:
      creationTimestamp: null
      name: traefik-config
      namespace: traefik

