apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-config
  namespace: traefik
spec:
  encryptedData:
    config.yaml: AgAiWjFSfw/vRGzvIZT5nJO0Oh8RbA3wd7u1NsVMlpoTykcHY6mCfuvh1K+9eyJ7ldqWPsMsdjp262RtpxlszPg5OvLCVEyZ02sNx/Xur1tZp6XoVnH7rYUKWhvgKTesX0lYu/jj5GkCwOJ48tusTBMjBiQ3cMe/cfc02xyjLsamGTonAdtBKy+oyy/2SlykL30bvlD+/QIPOnMdelSAkCR0Hdw4OycmTh+CI6tVpMiIpZAAr5s+5CWI/4kii89vfHQKvoDAZPx4yYGyNYO77pgoVpfuuitqXt0BMVsTOwH2YLOAorP2fkEoVR8I/MweBE064TO0VBRWq5RqH19liiWfMD3N/7FNqRoy5yEdODhbQxOPpF70FFQEAuGSKR9XZDJ39Ny8Wf+W1TGCyeAxU69tKFt40XCx/sKO+zFGCKoEF+VlKg3sGRMMfL+kR9I2r01rIElBFUmLNsO2rHqVlO53KDevbanQyFimneX3zq548/FJ3KwAOiGLV5sA0ukFrmjEzmgIkFse8KSyzREsQMP2fWdeWoZBHVqN2LDz0LZ46/Hkldjvpq+4VHu5QyS3PzVskM2HOGQHBBX9rlVB0PBJ8Oz6WHo44KEsyYnyH6Qz4jxJCzl77rY0d9LIsGm7WoMW8+fFIxM/eZIn9e19S3NRom3raaNl+08fZFPu3TyTkP762W8Lp4MbeMPSn3wYK1Xwd8IgEOS+CAv/w7/rm0c577e0FYLGQgscoQ+PrP2fmdANZmeeIbb9BPHmESXStQCmIjnq6fI+qPEVSzZo7QuoodQm/OQRhNKaTeFwHEQqTRLkUrCE4z40ovKGtSdN9IcjrFg60d9Ba4U0V3YtxHZmLTQomDLbpvPBxt4mfrBtVWMb02tpXT6krbVCcfRKKwjT3zc0996WekT8pEdnCMT6grFEoeFwLghl1NbuGLN3U2+FaZXKc9pUQItKlA7XyYcmA3kYFsed05LuXxuvK4LTvSp7ufiTpvES5UJWodpjiFe1g6JowQE/xr+YB8jnUMmxsw3CDehhFGhrIrIzuw57FegOaBcsHjfeyDZy0UM/a1D4alQoICbbKSTzInECu5Jjk3yU0nq9Hanrduf6LK54Ux8M78xIIOngXlz0bi3YTELp4HoAwLuTc3qqh1wpDsSe3o9QKlg5wmKXF4pRIt489s/BNAW+uP2qiIZxTLTsEr0nvj0o1374qcDJG7at58c/kE0+fkU+QST8UVOjL/+JM9y8hfRr57DVo4zMOxWhBWUf3oHRWfy4LiyUoTlJaCNQ9AX/lGjaXRGuclG9ox6L2iSlQQ==
  template:
    metadata:
      creationTimestamp: null
      name: traefik-config
      namespace: traefik

