apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-config
  namespace: traefik
spec:
  encryptedData:
    config.yaml: AgCN2mVxl68/fdRT+AqWd7CraXzMPZd1lUylSUhRciE4Xjc5ZqFPwVn8gJWXf1+i6jz5s7RYKpbFWTA9GUUEmjYtKbdLvzHJIwzCla+ZZM11aj+AXJPpmWEijKXCW3IJCTjN+SPsY/UIleVftx2rsW1xok7OfZbI1CFEOp3HrF0jX9+RC4ZC5zAl9jU2c+yoJkTpcUe31S/TD668wAutt+3GQVllL5+c8hI0p3cy+1OOQxE9wP1ncpkKcdkRaaJqv8lBQp8hIFVOkOElnWv7pPpeBONGRGGl7kpUDu5Yn9x+fpgV1r5hMtIYw5fw+4mI3etVhmEzIPYTqtQAdpwwEgMuKt8xlONq5cKvx6DP5WuCegLYFl3PA64hF/+epu3pP8hTWyD6bFiJnYhZcSyqD0cY7MM3ZF/QdG3V7Ovz1+09qmt0zgHqNlSWQ9mjK31eWR2DMUMbZb3X5lIV/OJ2aZSk3wYahvNZ+aXaFrogTr9vbuWHPPkzkF3eCMgEwlT8iy0br6p9f+ZHcDexEFFPBubjqc2MFWNo96RmfzKwh0Oiinodm+GWQyjXk77PbxsirvNv2WyVLwRK8mAo6NUK2c5n3YqDDMYSAt4LPFzc8X+yD9l3Y2LeKyCj3Gj0NHnWVRbw2HExUnN+b8tosNyNU2aAsmJBArsjwpZcWRRUIOz1Lul+u3ll8FvMO9FHMRQ156i39CYWjtKjhM+n5Qb8L2bcKMWPjryc5UvL9KvOvyNDrei2llY6BOHhhlr03M9MNzVLfqj6l2Ds99VyVsMTyJVNdGAgO6DyMXpIeCUzDhlszffPLNUeyfjLGL0tInLvcGoKygFPSFhnF8pt0CD/dlmZ8mNUuTSEfD6k/PDuPK14dvJfFPpDgtph24DMz4aftHI9baHKZd8qLpe8W2QRr8ziaDzugcpIAjB3/b1EKsr9kIPQcusd0gxI/AcKL5L67r1pUOGSzjvE2GPjNoTunmWgMflbZKufx5FrZa8A8NWP+BvqGI0njwRjueZm82esD5PN2ZJ/bjSJxtfD9UH92xnZvVgCBCPJqehcaOy9hB9mLmHwCEdBl8R24pm/wevI96rZQoTULwc1ORqwxGUTZqWUmpRJlP+6viaRm0X7LuakJ4mEIVqA/QqWEUfBK4tU9+XgN7fmClpiQOAGWVJVfPEgPaI5MlrQsolPawR157pi+lKbOy1qpVxj+8GozOlAcUWC7N0C0bSXoKCKg11G/xolQM6wHX7DAbj3R853fuLGCq7LiTXePnDR8dRymuuMOG8xqibhMrZ/du7DkgE6+Y+fkghO5Q==
  template:
    metadata:
      creationTimestamp: null
      name: traefik-config
      namespace: traefik

